managementClusterName: rancher-turtles-integration

intervals:
  default/wait-controllers: ["15m", "10s"]
  default/wait-rancher: ["30m", "30s"]
  default/wait-delete-cluster: ["30m", "30s"]
  default/wait-gitpush: ["3m", "10s"]
  default/wait-consistently: ["30s", "5s"]

variables:
  # General Configuration
  NAMESPACE: "default"
  MANAGEMENT_CLUSTER_ENVIRONMENT: "isolated-kind" # supported options: eks, isolated-kind, kind
  USE_EXISTING_CLUSTER: "false"
  SKIP_RESOURCE_CLEANUP: "false"
  SKIP_DELETION_TEST: "false"
  ARTIFACTS_FOLDER: "_artifacts"

  # Kubernetes Configuration
  KUBERNETES_VERSION: "v1.36.1"
  KUBERNETES_MANAGEMENT_VERSION: "v1.36.1"
  RKE2_VERSION: "v1.36.0+rke2r1"

  # CLI Tool Paths
  HELM_EXTRA_VALUES_FOLDER: "/tmp"

  # Rancher Configuration
  RANCHER_VERSION: "v2.15.0"
  RANCHER_REPO_NAME: "rancher-latest"
  RANCHER_PATH: "rancher-latest/rancher"
  RANCHER_URL: "https://releases.rancher.com/server-charts/latest"
  RANCHER_FEATURES: ""
  RANCHER_HOSTNAME: "localhost"
  RANCHER_PASSWORD: "rancheradmin"
